### ISSUE TITLE
writelto cant' find tapes ready to mount

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#15]
After ltopers updates, formatlto works as expected but mountlto reports "Checked 1 decks and none appear to have tapes ready to mount."

That seems odd...

We are using the same workflow as before the recent update. Running remotely so no physical access to LTO deck.

**Comment by dericed** [comment]
How many decks do you have attached? And what is the output of `ltfs -f -o devname=0`?

**Comment by NMAAHC** [comment]
One deck. Quantum SuperLoader 16. So, tape slots of which we have two filled. But, since it is formatting the tapes correctly it must be able to talk to the drive ok...

/Users/medialab
≈:≈ mountlto
Checking for ready tapes...
Checked 1 decks and none appear to have tapes ready to mount.

/Users/medialab
≈:≈ ltfs -f -o  devname=0?
50f LTFS14000I LTFS starting, LTFS version 2.2.0.1 (5100), log level 2
50f LTFS14058I LTFS Format Specification version 2.2.0
50f LTFS14104I Launched by "ltfs -f -o devname=0?"
50f LTFS14105I This binary is built for Mac OS X 
50f LTFS14106I GCC version is 4.2.1 (Apple Inc. build 5666) (dot 3)
50f LTFS17087I Kernel version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
50f LTFS14063I Sync type is "time", Sync time is 300 sec
50f LTFS17085I Plugin: Loading "iokit" driver
50f LTFS17085I Plugin: Loading "unified" iosched
50f LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection
50f LTFS12158I Opening a device through iokit driver (0?)
50f LTFS12163I Cannot open device: failed to convert devname to devnumber (0?)
50f LTFS12012E Cannot open device: failed backend open call
50f LTFS10004E Cannot open device '0?'

**Comment by dericed** [comment]
I updated how `mountlto` looks for drives but not with `formatlto`, thus the discrepancy. For now, you could use `brew switch` to get back to the prior version. With the decks I tested on that command would provide either the tape serial or the deck serial as a backup, but in your case it gives neither. :-/

**Comment by BleakleyMcD** [comment]
Ah. Ok. We can switch back. Thank you!

**Comment by dericed** [comment]
I think the issue is in this [line](https://github.com/amiaopensource/ltopers/blob/61504cdb7c8a869b78d5f68404737c0ee5fb5783/mountlto#L36). This is intended to try to mount a tape with no target directory, which is expected to fail but also to collect some tape data in the process to [reused](https://github.com/amiaopensource/ltopers/blob/61504cdb7c8a869b78d5f68404737c0ee5fb5783/mountlto#L40) in the second mount.

However that first ltfs command appears to something get stuck (and gets stuck for days without ever quitting) so the deck is held busy by the process and unavailable. Perhaps we need to make sure that [the first ltfs process](https://github.com/amiaopensource/ltopers/blob/61504cdb7c8a869b78d5f68404737c0ee5fb5783/mountlto#L36) is terminated properly or find a different way to gather tape data (user input as before). Am a bit frustrated that there is no utility/command to simply query a drive/tape for status beyond supplying improperly formed mount commands.

**Comment by NMAAHC** [comment]
OK. Noted.

In the meantime, we are retrograding to 0.1.2_3 after updates.

**Comment by NMAAHC** [comment]
Any update on this? We are still on 0.1.2_3 because all later releases will not mount our tapes

**Comment by retokromer** [comment]
Hello @NMAAHC, could you possibly test the current HEAD or the last release, and report? Thank you!

**Comment by BleakleyMcD** [comment]
We will on Wednesday! Thanks!

**Comment by dericed** [comment]
Hi @BleakleyMcD, if --HEAD doesn't work, please send the outputs of these commands.

This is one supposed to count how many LTO decks are attached.
`system_profiler SPSASDataType | grep "SCSI Target Identifier"`


and also this is supposed to attempt to mount the tape (in order to get tape metadata) but then fail because there's no mount path. The metadata is then used in a subsequent mount with the added context from the intentionally failed one.
`ltfs -f -o devname=0`

**Comment by dericed** [comment]
@BleakleyMcD, also please provide the output of `ltfs -V`.

**Comment by NMAAHC** [comment]
HEAD didn't work :(

`/Users/medialab
≈:≈ brew reinstall --HEAD ltopers
==> Reinstalling amiaopensource/amiaos/ltopers 
==> Cloning git://github.com/amiaopensource/ltopers.git
Updating /Users/medialab/Library/Caches/Homebrew/ltopers--git
==> Checking out branch master
Error: No such file or directory - lto2filemaker`

`/Users/medialab
≈:≈  system_profiler SPSASDataType | grep "SCSI Target Identifier"
          SCSI Target Identifier: 0`

`/Users/medialab
≈:≈ ltfs -V
LTFS version 2.2.0.1 (5100)
LTFS Format Specification version 2.2.0`

**Comment by NMAAHC** [comment]
Looks like HEAD isn't installing because of a missing file.

**Comment by kieranjol** [comment]
I'd say that's because lto2filemaker was removed very recently but that isn't affected in the homebrew recipe. I left a pull request here. Hopefully that solves that particular issue anyhow: https://github.com/amiaopensource/homebrew-amiaos/pull/22

**Comment by dericed** [comment]
@BleakleyMcD, can you provide the output of `ltfs -f -o devname=0`

**Comment by dericed** [comment]
I just merged @kieranjol's fix, so `brew reinstall ltopers --HEAD` should (maybe) be okay again.

**Comment by NMAAHC** [comment]
`/Users/medialab
≈:≈ ltfs -f -o devname=0
50f LTFS14000I LTFS starting, LTFS version 2.2.0.1 (5100), log level 2
50f LTFS14058I LTFS Format Specification version 2.2.0
50f LTFS14104I Launched by "ltfs -f -o devname=0"
50f LTFS14105I This binary is built for Mac OS X 
50f LTFS14106I GCC version is 4.2.1 (Apple Inc. build 5666) (dot 3)
50f LTFS17087I Kernel version: Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64
50f LTFS14063I Sync type is "time", Sync time is 300 sec
50f LTFS17085I Plugin: Loading "iokit" driver
50f LTFS17085I Plugin: Loading "unified" iosched
50f LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection
50f LTFS12158I Opening a device through iokit driver (0)
50f LTFS12118I Drive identification is 'ULTRIUM-HH6     '
50f LTFS12162I Vendor ID is IBM     
50f LTFS12159I Firmware revision is E4J1
50f LTFS12160I Drive serial is 10WT045909
50f LTFS17160I Maximum device block size is 1048576
50f LTFS17157I Changing the drive setting to write-anywhere mode
50f LTFS11005I Mounting the volume
50f LTFS12207I Logical block protection is disabled
50f LTFS17227I Tape attribute: Vendor = IBM     
50f LTFS17227I Tape attribute: Application Name = LTFS                            
50f LTFS17227I Tape attribute: Application Version = 2.2.0.1 
50f LTFS17227I Tape attribute: Medium Label = LT032A
50f LTFS17228I Tape attribute: Text Localization ID = 0x81
50f LTFS17227I Tape attribute: Barcode = LT032A                          
50f LTFS17227I Tape attribute: Application Format Version = 2.2.0           
50f LTFS14094E Cannot get mount point (0)
50f LTFS12207I Logical block protection is disabled`

**Comment by dericed** [comment]
hmm, I haven't tested with that version of the utility before, can you provide the outputs of `ltfs -h` and `ltfs -a` as well.

**Comment by NMAAHC** [comment]
HEAD reinstalled correctly:
**/Users/medialab
≈:≈ brew reinstall --HEAD ltopers
==> Reinstalling amiaopensource/amiaos/ltopers 
==> Cloning git://github.com/amiaopensource/ltopers.git
Updating /Users/medialab/Library/Caches/Homebrew/ltopers--git
==> Checking out branch master
🍺  /usr/local/Cellar/ltopers/HEAD-5b2b463_3: 11 files, 22.4K, built in 1 second**

BUT we appear to still have the same issue:

/Users/medialab
≈:≈ mountlto
 Checking for ready tapes...
 Checked 1 decks and none appear to have tapes ready to mount.

**Comment by retokromer** [comment]
I haven’t testes IBM either, and cannot test those desks this week.

**Comment by NMAAHC** [comment]
Thank you!

/Users/medialab
≈:≈ ltfs -h && ltfs -a
50f LTFS17085I Plugin: Loading "iokit" driver
usage: ltfs mountpoint [options]

LTFS options:
    -o devname=<dev>          Tape device (default: 0)
    -o work_directory=<dir>   LTFS work directory (default: /tmp/ltfs)
    -o trace                  Enable diagnostic output (same as verbose=3)
    -o eject                  Eject the cartridge after unmount
    -o sync_type=<type>       Specify sync type (default: time@5)
                              <type> should be specified as follows:
                              time@min:  LTFS attempts to write an index each 'min' minutes.
                                         min should be a decimal number from 1 to 153722867280912930
                                         It is equivalent to "-o sync_type=unmount" when 0 is specified
                                         (default: min=5)
                              close:     LTFS attempts to write an index when a file is closed
                              unmount:   LTFS attempts to write an index when the medium is unmounted
    -o force_mount_no_eod     Skip EOD existence check when mounting (read-only mount)
                              Only use for a CM corrupted medium
    -o device_list            Show available tape devices
    -o rollback_mount=<gen>   Attempt to mount on previous index generation (read-only mount)
    -o release_device         Clear device reservation (should be specified with -o devname
    -o symlink_type=<type>    Specify symbolic link type (default: posix)
                              <type> should be specified with one of the following values:
                              posix:  LTFS behavior is same as standard symbolic link
                              live:   LTFS replaces mount point path by current mount point
    -a                        Advanced help, including standard FUSE options
    -V, --version             Output version information and exit
    -h, --help                Display this help and exit

FUSE options:
    -o umask=M                Set file permissions (octal)
    -o uid=N                  Set file owner
    -o gid=N                  Set file group


usage: ltfs mountpoint [options]

general options:
    -o opt,[opt...]        mount options
    -h   --help            print help
    -V   --version         print version

FUSE options:
    -d   -o debug          enable debug output (implies -f)
    -f                     foreground operation
    -s                     disable multi-threaded operation

no mount point

LTFS options:
    -o config_file=<file>     Configuration file (default: /Library/Frameworks/LTFS.framework/Versions/Current/etc/ltfs.conf)
    -o work_directory=<dir>   LTFS work directory (default: /tmp/ltfs)
    -o atime                  Update index if only access times have changed
    -o noatime                Do not update index if only access times have changed (default)
    -o tape_backend=<name>    tape backend to use (default: iokit)
    -o iosched_backend=<name> I/O scheduler implementation to use (default: unified, use "none" to disable)
    -o kmi_backend=<name>     Key manager interface implementation to use (default: none, use "none" to disable)
    -o umask=<mode>           Override default permission mask (3 octal digits, default: 000)
    -o fmask=<mode>           Override file permission mask (3 octal digits, default: 000)
    -o dmask=<mode>           Override directory permission mask (3 octal digits, default: 000)
    -o min_pool_size=<num>    Minimum write cache pool size. Cache objects are 1 MB each (default: 25)
    -o max_pool_size=<num>    Maximum write cache pool size. Cache objects are 1 MB each (default: 50)
    -o rules=<rules>          Rules for choosing files to write to the index partition.
                              The syntax of the rule argument is:
                              size=1M
                              size=1M/name=pattern
                              size=1M/name=pattern1:pattern2:pattern3
                              A file is written to the index partition if it is no larger
                              than the given size AND matches at least one of the name
                              patterns (if specified). The size argument accepts K, M, and G
                              suffixes. Name patterns might contain the special characters
                              '?' (match any single character) and '*' (match zero or more
                              characters).
    -o quiet                  Disable informational messages (same as verbose=1)
    -o trace                  Enable diagnostic output (same as verbose=3)
    -o syslogtrace            Enable diagnostic output to stderr and syslog(same as verbose=303)
    -o fulltrace              Enable full call tracing (same as verbose=4)
    -o verbose=<num>          Override output verbosity directly (default: 2)
    -o eject                  Eject the cartridge after unmount
    -o noeject                Do not eject the cartridge after unmount (default)
    -o sync_type=<type>       Specify sync type (default: time@5)
                              <type> should be specified as follows:
                              time@min:  LTFS attempts to write an index each 'min' minutes.
                                         min should be a decimal number from 1 to 4294967292
                                         It is equivalent to "-o sync_type=unmount" when 0 is specified
                                         (default: min=5)
                              close:     LTFS attempts to write an index when a file is closed
                              unmount:   LTFS attempts to write an index when the medium is unmounted
    -o force_mount_no_eod     Skip EOD existence check when mounting (read-only mount)
                              Only use for a CM corrupted medium
    -o device_list            Show available tape devices
    -o rollback_mount=<gen>   Attempt to mount on previous index generation (read-only mount)
    -o release_device         Clear device reservation (should be specified with -o devname
    -o capture_index          Capture latest index to work directory at unmount
    -o scsi_append_only_mode=<on|off>  Set the tape device append-only mode (default=on)
    -a                        Advanced help, including standard FUSE options

50f LTFS17085I Plugin: Loading "iokit" driver
IOKIT backend options:
    -o devname=<dev>          tape device (default=0)
    -o scsi_lbprotect=<on|off> enable drive logical block protection (default=off)

50f LTFS17085I Plugin: Loading "file" driver
FILE backend options:
    -o devname=<dev>          LTFS emulation directory (default=/tmp/ltfs/tape)
    -o file_readonly          Emulate operation in read-only mode
    -o file_p0_warning=<num>  Set early warning position partition 0
    -o file_p1_warning=<num>  Set early warning position partition 1

50f LTFS17085I Plugin: Loading "itdtimg" driver
(no message found)
50f LTFS17085I Plugin: Loading "flatfile" kmi
Key manager interface flatfile plug-in options:
    -o kmi_dki_for_format=<DKi>
                              Data key identifier to format a cartridge
    -o kmi_dk_list=FILE
                              Data key and data key identifier pairs' list file


50f LTFS17085I Plugin: Loading "simple" kmi
Key manager interface simple plug-in options:
    -o kmi_dk=<DK>
                              Data key
    -o kmi_dki=<DKi>
                              Data key identifier
    -o kmi_dk_for_format=<DK>
                              Data key to format a cartridge
    -o kmi_dki_for_format=<DKi>
                              Data key identifier to format a cartridge
    -o kmi_dk_list=<DK>:<DKi>/<DK>:<DKi>/.../<DK>:<DKi>
                              Data key and data key identifier pairs' list

**Comment by dericed** [comment]
the versions of the utilities report the barcode quite differently:
`50f LTFS17227I Tape attribute: Barcode = LT032A`
vs
`50f LTFS10024I Volser(Barcode) : D00081`

I'll add in some conditions to catch both styles.

**Comment by dericed** [comment]
Hi @BleakleyMcD, can you update (after https://github.com/amiaopensource/ltopers/commit/f0108b68e85b0c07853247854bb6abbf52f215ad) and retry?

**Comment by NMAAHC** [comment]
Yes! Many many thanks!

/Users/medialab
≈:≈ mountlto
 Checking for ready tapes...
Deck 0 found with tape LT032A
 MOUNTING TAPE : THE TAPE WILL MOUNT TO THE /Volumes/LT032A FOLDER
 MOUNTING TAPE : AFTER MOUNT PRESS CONTROL-C$ TO EJECT
50f LTFS14000I LTFS starting, LTFS version 2.2.0.1 (5100), log level 2
50f LTFS14058I LTFS Format Specification version 2.2.0
50f LTFS14104I Launched by "ltfs -f -o work_directory=/Users/medialab/Documents/lto_indexes -o eject -o noatime -o capture_index -o devname=0 -o volname=LT032A -o uid=503 /Volumes/LT032A"
50f LTFS14105I This binary is built for Mac OS X 
50f LTFS14106I GCC version is 4.2.1 (Apple Inc. build 5666) (dot 3)
50f LTFS17087I Kernel version: Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64
50f LTFS14063I Sync type is "time", Sync time is 300 sec
50f LTFS17085I Plugin: Loading "iokit" driver
50f LTFS17085I Plugin: Loading "unified" iosched
50f LTFS12158I Opening a device through iokit driver (0)
50f LTFS12118I Drive identification is 'ULTRIUM-HH6     '
50f LTFS12162I Vendor ID is IBM     
50f LTFS12159I Firmware revision is E4J1
50f LTFS12160I Drive serial is 10WT045909
50f LTFS17160I Maximum device block size is 1048576
50f LTFS17157I Changing the drive setting to append-only mode
50f LTFS11005I Mounting the volume
50f LTFS12207I Logical block protection is disabled
50f LTFS17227I Tape attribute: Vendor = IBM     
50f LTFS17227I Tape attribute: Application Name = LTFS                            
50f LTFS17227I Tape attribute: Application Version = 2.2.0.1 
50f LTFS17227I Tape attribute: Medium Label = LT032A
50f LTFS17228I Tape attribute: Text Localization ID = 0x81
50f LTFS17227I Tape attribute: Barcode = LT032A                          
50f LTFS17227I Tape attribute: Application Format Version = 2.2.0           
50f LTFS14111I Initial setup completed successfully
50f LTFS14112I Invoke 'mount' command to check the result of final setup
50f LTFS14113I Specified mount point is listed if succeeded
50f LTFS14029I Ready to receive file system requests
